---

# Ref: https://cirrus-ci.org/guide/writing-tasks/

# Global environment variables
env:
    # Name of the typical destination branch for PRs.
    DEST_BRANCH: "main"


# Default task runtime environment
container:
    dockerfile: ci/Dockerfile
    cpu: 1
    memory: 1


# Execute all unit-tests in the repo
cirrus-ci/test_task:
    env:
        CIRRUS_CLONE_DEPTH: 0
    script:
        - git fetch --tags |& tee /tmp/test_output.log
        - $CIRRUS_WORKING_DIR/bin/run_all_tests.sh |& tee -a $CIRRUS_WORKING_DIR/output.log
    always:
        test_output_artifacts:
            path: '*.log'


# Represent primary Cirrus-CI based testing (Required for merge)
cirrus-ci/success_task:
    depends_on:
        - cirrus-ci/test
    clone_script: mkdir -p "$CIRRUS_WORKING_DIR"
    script: >-
        echo "Required for Action Workflow: https://github.com/${CIRRUS_REPO_FULL_NAME}/actions/runs/${GITHUB_CHECK_SUITE_ID}"


# Represent secondary Github Action based testing (Required for merge)
# N/B: NO other task should depend on this task. Doing so will prevent
#      the cirrus-ci_retrospective github action.  This is because the
#      action trigers `on: check-suite: completed` event, which cannot
#      fire since the manual task has dependencies that cannot be
#      satisfied.
github-actions/success_task:
    # Note: ***DO NOT*** manually trigger this task under normal circumstances.
    #       It is triggered automatically by the cirrus-ci_retrospective
    #       Github Action.  This action is responsible for testing the PR changes
    #       to the action itself.
    trigger_type: manual
    # Only required for PRs, never tag or branch testing
    only_if: $CIRRUS_PR =~ '.*[0-9]+.*'
    depends_on:
        - cirrus-ci/test
    clone_script: mkdir -p "$CIRRUS_WORKING_DIR"
    script: >-
        echo "Triggered by Github Action Workflow: https://github.com/${CIRRUS_REPO_FULL_NAME}/actions/runs/${GITHUB_CHECK_SUITE_ID}"
