---

# Ref: https://cirrus-ci.org/guide/writing-tasks/

# Global environment variables
env:
    # Name of the typical destination branch for PRs.
    DEST_BRANCH: "master"

# Default task runtime environment
container:
    image: quay.io/libpod/cirrus-ci_retrospective:latest
    cpu: 1
    memory: 1

# Execute all unit-tests in the repo
cirrus-ci/test_task:
    env:
        CIRRUS_CLONE_DEPTH: 0
    script:
        - git fetch --tags |& tee /tmp/test_output.log
        - $CIRRUS_WORKING_DIR/bin/run_all_tests.sh |& tee -a /tmp/output.log
    always:
        test_output_artifacts:
            path: '/tmp/*.log'

# Represent primary Cirrus-CI based testing (Required for merge)
cirrus-ci/success_task:
    alias: cirrus-ci/success
    depends_on:
        - cirrus-ci/test
    noop_script: /bin/true

# Represent secondary Github Action based testing (Required for merge)
github-actions/success_task:
    alias: github-actions/success
    # Note: ***DO NOT*** manually trigger this task under normal circumstances.
    #       It is triggered automatically by the cirrus-ci_retrospective
    #       Github Action.  This action is responsible for testing the PR changes
    #       to the action itself.
    trigger_type: manual
    # Only required for PRs, never tag or branch testing
    only_if: $CIRRUS_BRANCH != $DEST_BRANCH
    depends_on:
        - cirrus-ci/test

    noop_script: /bin/true

