---

# Ref: https://cirrus-ci.org/guide/writing-tasks/

# Default task runtime environment
container:
    image: quay.io/libpod/cirrus-ci_retrospective:latest
    cpu: 1
    memory: 1

# Execute all unit-tests in the repo
cirrus-ci/test_task:
    env:
        CIRRUS_CLONE_DEPTH: 0
    script:
        - git fetch --tags |& tee /tmp/test_output.log
        - $CIRRUS_WORKING_DIR/bin/run_all_tests.sh |& tee -a /tmp/output.log
    always:
        test_output_artifacts:
            path: '/tmp/*.log'

# Must pass for automatic-merge to occur, see .mergify.yml
cirrus-ci/success_task:
    alias: cirrus-ci/success

    depends_on:
        - cirrus-ci/test

    noop_script: /bin/true
